version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./backend/alarms.json:/app/alarms.json
    environment:
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=80
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/api/alarms"]
      interval: 30s
      timeout: 10s
      retries: 3 