services:
  alarmy:
    container_name: alarm_backend
    build:
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./backend/alarms.json:/app/backend/alarms.json
    environment:
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=80
    restart: unless-stopped
