[build]
target = "thumbv6m-none-eabi"

[target.thumbv6m-none-eabi]
rustflags = [
    "-C",
    "link-arg=-Tlink.x",
    "-C",
    "link-arg=-Tdefmt.x"
]

runner = [
    "probe-rs",
    "run", 
    "--chip",
    "RP2040",
    "--log-format",
    "{t} {l} {s}"
]

[env]
DEFMT_LOG = "debug"